version: "3"

services:
  namenode:
    image: hadoop_namenode:3.1.2
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
      - fluentd_hadoop

  datanode01:
    image: hadoop_datanode:3.1.2
    container_name: datanode01
    hostname: datanode01
    ports:
      - "9864:9864"
    volumes:
      - datanode01:/opt/hadoop/dfs/data
    networks:
      - fluentd_hadoop

  resourcemanager:
    image: hadoop_resourcemanager:3.1.2
    container_name: resourcemanager
    hostname: resourceamanager
    ports:
      - "8088:8088"
      - "8031:8031"
    networks:
      - fluentd_hadoop

  nodemanager01:
    image: hadoop_nodemanager:3.1.2
    container_name: nodemanager01
    hostname: nodemanager01
    networks:
      - fluentd_hadoop

volumes:
  namenode:
  datanode01:

networks:
  fluentd_hadoop:
